---
title: "Publications"
editor: visual
---

::: callout-note
## Links

> -   **Google Scholar**: <https://scholar.google.com/citations?user=dkkQZlgAAAAJ&hl=zh-CN>
> -   **ORCID**: <https://orcid.org/0000-0002-5333-4704>
> -   **ResearchGate:** <https://www.researchgate.net/profile/Jian-Ye-3/research>
:::

 

## Selected Publications

-   **J. Ye**, W. Xuan, Q. Guo, Y. Liu, B. Wang, X. Zhang and H. H. C. Iu, "An overview of reinforcement learning for power electronic converters: Topology derivation, parameter design, and control implementation," Renewable and Sustainable Energy Reviews, Mar. 2026. [-Link-](https://www.sciencedirect.com/science/article/pii/S136403212501264X?dgcid=author)
-   **J. Ye**, H. Guo, B. Wang and X. Zhang, "Deep Deterministic Policy Gradient Algorithm Based Reinforcement Learning Controller for Single-Inductor Multiple-Output DC–DC Converter," IEEE Transactions on Power Electronics, vol. 39, no. 4, pp. 4078-4090, Apr. 2024. [-Link-](https://ieeexplore.ieee.org/abstract/document/10381868)
-   **J. Ye**, H. Guo, D. Zhao, B. Wang and X. Zhang, "TD3 Algorithm Based Reinforcement Learning Control for Multiple-Input Multiple-Output DC–DC Converters," IEEE Transactions on Power Electronics, vol. 39, no. 10, pp. 12729-12742, Oct. 2024. [-Link-](https://ieeexplore.ieee.org/abstract/document/10564013)
-   **J. Ye** et al., "Improving Voltage Regulation of Interleaved DC–DC Boost Converter via Soft Actor–Critic Algorithm-Based Reinforcement Learning Controller," IEEE Journal of Emerging and Selected Topics in Power Electronics, vol. 13, no. 5, pp. 5958-5969, Oct. 2025.
-   **J. Ye** et al., "Soft Actor-Critic Algorithm Based Reinforcement Learning Controller for Single-Inductor Dual-Output DC-DC Converter," IEEE Journal of Emerging and Selected Topics in Industrial Electronics, vol. 6, no. 4, pp. 1478-1490, Oct. 2025.
-   **J. Ye**, H. B. Gooi and F. Wu, "Optimization of the Size of UPQC System Based on Data-Driven Control Design," IEEE Transactions on Smart Grid, vol. 9, no. 4, pp. 2999-3008, Jul. 2018.
-   **J. Ye**, H. B. Gooi and F. Wu, "Optimal Design and Control Implementation of UPQC Based on Variable Phase Angle Control Method," IEEE Transactions on Industrial Informatics, vol. 14, no. 7, pp. 3109-3123, Jul. 2018.
-   **J. Ye**, H. B. Gooi, B. Wang and X. Zhang, "A New Flexible Power Quality Conditioner With Model Predictive Control," IEEE Transactions on Industrial Informatics, vol. 15, no. 5, pp. 2569-2579, May 2019.
-   **J. Ye** and H. B. Gooi, "Phase Angle Control Based Three-phase DVR with Power Factor Correction at Point of Common Coupling," Journal of Modern Power Systems and Clean Energy, vol. 8, no. 1, pp. 179-186, Jan. 2020.
-   **J. Ye**, H. B. Gooi, X. Zhang and H. H. C. Iu, "Simplified Four-Level Inverter-Based Single-Phase DSTATCOM Using Model Predictive Control," IEEE Journal of Emerging and Selected Topics in Power Electronics, vol. 8, no. 4, pp. 3382-3395, Dec. 2020.